
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umultzfwelmcrptunfif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtdWx0emZ3ZWxtY3JwdHVuZmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODIwMTMsImV4cCI6MjA1Nzg1ODAxM30.d_bBE1w2F4TZliD_a1PYn2DjUZB6tSKpcveDppm8W5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
